### ISSUE TITLE
Add end to end -tests

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#10]
#### Proposed solution

Create tests for testing UI, frontend logic and backend together. This can be done with either Selenium or Cypress (I'd prefer latter, it's easier to use) and docker (for running backend and db).

End to end tests should also be integrated to CI pipeline. 

#### DoD (Definition of Done)

Core functionalities are tested.

**Comment by blankdots** [comment]
we also need to add them to github actions and test for default broswers such as Chrome and Firefox
