### ISSUE TITLE
Handle additional folder draft operations

### ISSUE THREAD

**Issue by csc-jm** [CSCfi/metadata-submitter-frontend#101]
#### Proposed solution

After refactoring the folders to include drafts in the backend in [#144](https://github.com/CSCfi/metadata-submitter/pull/144), the frontend needs to take this into account. This means, when drafts are created, the folder where the draft belongs in should be patched accordingly. Also for publishing a folder, there is a new endpoint `/publish/{folderId}`. This endpoint discards the unfinished drafts within the folder and deletes them from the draft database collection. Therefore, upon publishing the user should be alerted that the drafts will be discarded.

#### DoD (Definition of Done)

-Additional `PATCH` operations are added for adding and removing drafts in folders
-Alerts are added for when folders are being published and drafts within the folders will be removed

**Comment by blankdots** [comment]
dependent also on https://github.com/CSCfi/metadata-submitter/issues/153

**Comment by saulipurhonen** [comment]
Pending on #67
