### ISSUE TITLE
Create folders and draft lists in home page

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#115]
#### Description

According to design we need to call the API and list user's drafts and folders
![image](https://user-images.githubusercontent.com/47524/102251182-243c7a00-3f0d-11eb-8524-6dd4488d9835.png)

![image](https://user-images.githubusercontent.com/47524/102251725-e0964000-3f0d-11eb-99de-fbac38c4b40c.png)

User can have 2 types of drafts under `/users/<userid>` (in the json response there is a `draft` key (an array of accession ids) and a similar one is in `fodlers` objects under `drafts` key (array of objects with schema and accession id).

#### DoD (Definition of Done)

the folder and draft list functionality reflects the UI design

#### Testing

unit test and if possible integration tests

**Comment by hannyle** [comment]
I suppose the `drafts` in `folders` are unpublished folders, and the `drafts` in `users` are draft objects, which mean they are different. Am i correct?
But at the same time, in `folders` we have `published: boolean` which can also contain both published folders and unpublished folders. I am a bit confused here.

**Comment by blankdots** [comment]
@hannyle not quite, but close

1. when a `folder` is published all remaining `drafts` from `folders` will go under `user `> `drafts` and the intent is to later use them as templates - this has not been done in backend but there is an issue about it https://github.com/CSCfi/metadata-submitter/issues/160 - however the task is not dependent on this, i think it can be implemented without it
1.1. the `drafts` will be saved only if the user requests to do so otherwise they will get deleted. If I remember correctly there is a modal/pop-up window when a user publishes and that is when we can have a checkbox with keep `drafts` from current folder as templates
2. A `folder` can have its own `drafts` when it is unpublished, but also `metadataObjects` for a certain schema that are submitted.

In order to make it easier we can have as follows:
1. `Your Draft submissions` contains folders that are unpublished (can contain both `drafts` and `metadataObjects` associated to a `folder`  see https://github.com/CSCfi/metadata-submitter/blob/master/metadata_backend/helpers/schemas/folders.json response from Folders API
2. `Your published submissions` contain folders that are published with `metadataObjects`
3. `Your saved templates` contains `drafts` from `users`  see https://github.com/CSCfi/metadata-submitter/blob/master/metadata_backend/helpers/schemas/users.json response from Users API

or we can have:
1.  `Your folders` contain `folders` published or unpublished (we should be able to distinguish between them via a label of some sort)
2. `Your templates` contains `user` > `drafts`

Not sure what would be an ideal option. I am biased and would do the first one with 3 categories, but I leave it to whoever implements.

**Comment by hannyle** [comment]
Fixed according to suggestions.
And here are follow-up features for future discussion:
https://github.com/CSCfi/metadata-submitter-frontend/issues/138
https://github.com/CSCfi/metadata-submitter-frontend/issues/139

**Comment by blankdots** [comment]
We should also have a listing for draft templates for a user but that is dependent on backend https://github.com/CSCfi/metadata-submitter/issues/160 for now closing the issue and continuing in https://github.com/CSCfi/metadata-submitter-frontend/issues/141
