### ISSUE TITLE
Option to cancel editing a saved draft 

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter-frontend#135]
#### Proposed solution

I a saved draft is opened from `Choose from drafts`, it opens a form with pre-filled values.
- However if a user change his/her mind and doesn't want to continue with this draft and have a new empty form, there should be a way for the user to escape/cancel from editing the current draft. 

#### DoD (Definition of Done)

User is able to create a new form (from an existing form)

#### Testing

e2e test, peer to peer review

**Comment by blankdots** [comment]
we can have a sticky bar that contains form controls such as:
1. clear form
2. new form
3. save draft
4. submit <object>

we don't need the `hide` button.
