### ISSUE TITLE
Add edit and delete functionality to submitted objects

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#144]
#### Description

We need to be able to resume editing an object, the submission summary on the right hand side should contain a button group with edit and delete

![image](https://user-images.githubusercontent.com/47524/106496483-9a993980-64c5-11eb-8aa4-745addd31c30.png)

The same goes for the summary at the end of the submission:

![image](https://user-images.githubusercontent.com/47524/106496659-d207e600-64c5-11eb-9e3d-d7fb656d4fb8.png)

#### DoD (Definition of Done)

Ability to edit and delete submitted objects.

#### Testing

Unit test and Integration testing

**Comment by saulipurhonen** [comment]
@blankdots what about XML uploads? Those show in the listing too but I think edit functionality would be weird since only option would be to replace the file. I suggest that we show only delete button on XML submissions. This requires #94 so we can get submission type for metaDataObjects.

**Comment by blankdots** [comment]
yes, XML uploads probably the only way to edit would be to re-upload
