### ISSUE TITLE
Multiple API-calls on home page

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#150]
#### Describe the bug

Loading `Draft` and `Published` submissions sends API call for each folder found for user. This is really performance heavy operation and should be queried with maximum 2 calls.

#### To Reproduce

1. Save multiple Draft folders
2. Publish multiple different folders
3. Go to /home
4. Check browser dev tools for `Network` tab

#### Expected behavior

Users folders should be queried with minimum API calls.

**Comment by saulipurhonen** [comment]
@blankdots, what kind of queries are possible to be made against the backend regarding this issue?

**Comment by blankdots** [comment]
@saulipurhonen 
1. GET `user` API retrieves a list of `folders` IDs and `drafts` IDs (templates or drafts not attached to a folder)
2. GET `folders` API retrieves `metadataObjects` IDs and `drafts` IDs attached to a folder (this is needed for seeing which folder is published)

The first call i remember it is set in state so to list the folders only the 1st call should be needed, but to see which one is published you need the 2nd call
