### ISSUE TITLE
Having a file to contain commonly used dataTypes

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter-frontend#157]
#### Description

Currently there are many `variables` and `props` being reused in different `components` and `features`. Their **dataTypes** are written repeatedly many times here and there. Sometimes it's a bit hard to keep track all of them and they may be inconsistent when the application gets bigger.

#### DoD (Definition of Done)

Having one file that contained **dataTypes** that are commonly used so we don't have to repeat the codes

#### Testing

Peer to peer

**Comment by blankdots** [comment]
I suggest taking a look at the json schemas in: https://github.com/CSCfi/metadata-submitter/tree/develop/metadata_backend/helpers/schemas for potential values
