### ISSUE TITLE
Having a constant file to contain enum values

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter-frontend#158]
#### Description
Currently there are many variables that are manually assigned their values in some files. 
For example, `submissionType` can have values as `"form"` or `"XML"` or `"Form"` or `"xml"`
The values are inconsistent and we are kind of hard-coding them. This can cause more bugs and hard to keep track in the future if the application gets bigger.

#### DoD (Definition of Done)
Having a file contained `enums` to define a set of constants

#### Testing
Peer to peer

**Comment by blankdots** [comment]
there is a json schema validation in the backend which has the `enum` https://github.com/CSCfi/metadata-submitter/blob/develop/metadata_backend/helpers/schemas/folders.json#L44-L61 I haven't tried but not sure sending different cases than what is specified would work. are we sure it is possible ?

Or this is just for front-end to have a list of predefined values ?

**Comment by hannyle** [comment]
> there is a json schema validation in the backend which has the `enum` https://github.com/CSCfi/metadata-submitter/blob/develop/metadata_backend/helpers/schemas/folders.json#L44-L61 I haven't tried but not sure sending different cases than what is specified would work. are we sure it is possible ?
> 
> Or this is just for front-end to have a list of predefined values ?

Yes, it is just for front-end to have `enums`, instead of hard-coding like now. For example:
- Instead of:
> switch (months) {
	case "Jan":
	// Jan
	case "Feb":
	// Feb
	case "March":
	// Mar	
}

- I would have:

> const months = {
	JAN: "january",
	FEB: "february",
	MAR: "march",
}

> switch (season) {
	case seasons.JAN:
	// Jan
	case seasons.FEB:
	// Feb
	case seasons.MAR:
        // Mar
}
