### ISSUE TITLE
WizardShowSummary lacks of Object type "Dataset"

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter-frontend#167]
#### Describe the bug

**Dataset** belongs to Objects list,  but it doesn't exist in the **Summary**

#### To Reproduce

Steps to reproduce the behaviour:

1. Go to 'Create Submission'
2. Fill in Folder name and description
2. Click 'Next'
3. See "Dataset" at the end of the list of Objects on left side
4. Click 'Next'
5. In the Summary there is no "Dataset" object anymore

#### Expected behavior

**Dataset** and its submitted objects shows in the Summary

**Comment by blankdots** [comment]
my bad closed it without looking
