### ISSUE TITLE
Fix keyboard-based xml file upload

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#20]
#### Describe the bug

User needs to press tab once more after the "choose file" -button is focused in upload xml page.

#### To Reproduce

Steps to reproduce the behaviour:

1. Go to page where user can upload an xml file
2. Browse to choose file with tab (so choose file is focused)
3. Click enter
4. Nothing happens
5. Press tab once more
6. Click enter
7. Native file chooser opens

#### Expected behavior

Expected browser to open native file chooser when choose file is focused.

#### Additional context

This is probably caused by material ui:s formcontrol  API being too aggressive about form element responsibilities. 

Original idea for file inputs is from here: https://benmarshall.me/styling-file-inputs/. Note that `display: none` or `visibility: hidden` do not work as a solution!

**Comment by lilachic** [comment]
Being investigating this and not sure if keyboard and using tab is consistent in this UI. First the order needs to be figured out.

**Comment by lilachic** [comment]
"Return to homepage" also seem tohave this issue, after submission at least.
