### ISSUE TITLE
Edit does not work for all fields

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#256]
#### Describe the bug

Edit does not seem to work for all fields for `Sample`, `Experiment`, `Analysis` and `Run`

Please add integration tests to prevent this from happening

#### To Reproduce

Steps to reproduce the behaviour:

1. Go to `Create Submission` to create folder
2. Click on an object `Sample` 
3. Fill in form with required filed and also `Sample Data Type`
4. Submit form
5. clear form
6. edit previous form and see how `Sample Data Type` does not get proper data
7. See screenshots for other schema types

#### Expected behavior

 `Sample Data Type` for `Sample` does gets proper data when edit is pressed
All fields get the right information to edit.

#### Screenshots

`Sample`

![Peek 2021-04-19 13-15](https://user-images.githubusercontent.com/47524/115220689-8272a700-a111-11eb-800e-ce7692863b00.gif)

----

`Experiment`

![Peek 2021-04-19 14-28](https://user-images.githubusercontent.com/47524/115229347-9b805580-a11b-11eb-935f-47501777ca50.gif)

----

`Run`

![Peek 2021-04-19 14-30](https://user-images.githubusercontent.com/47524/115229498-cbc7f400-a11b-11eb-8e60-7328ac71964b.gif)

----

`Analysis`
![Peek 2021-04-19 14-31](https://user-images.githubusercontent.com/47524/115229726-0e89cc00-a11c-11eb-9891-10b36348ab7a.gif)

**Comment by saulipurhonen** [comment]
#294 is blocking testing for possible solution.
