### ISSUE TITLE
Submitted object edit

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#292]
#### Describe the bug

Form doesn't get populated with selected object details if user has cleared the form.

#### To Reproduce

Steps to reproduce the behaviour:

1. Submit a form
2. Click edit from submitted object list
3. Click `Clear form`
4. Click edit from submitted object list again

#### Expected behavior

Form should be populated with chosen object details.

**Comment by saulipurhonen** [comment]
To fix:
Dispatch a `resetObject` method when clearing the form.

**Comment by blankdots** [comment]
related to #256 ?

**Comment by saulipurhonen** [comment]
> related to or duplicate of #256 ?

Neither. In #256 it seems that the problem is within populating the form. In this issue the problem is how the form clear-method handles current object in redux state.
