### ISSUE TITLE
Edit Experiment draft

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#294]
#### Describe the bug

Application errors with `TypeError: Cannot add property spotDescriptor, object is not extensible` when user tries to edit `experiment` draft object

#### To Reproduce

Steps to reproduce the behaviour:

1. Save an `experiment` form as a draft
2. Try to edit newly saved draft

#### Expected behavior

Form should be populated without errors.

**Comment by saulipurhonen** [comment]
This seems to be related in React Hook Form `useFieldArray` method in `WizardJSONSchemaParser` `FormArray` method.
Form renders without errors if `useFieldArray` is disabled.

**Comment by saulipurhonen** [comment]
This also happens while trying to edit `analysis` form if eg. `Analysis type` and it's children has been filled. Error message: `TypeError: Cannot assign to read only property 'referenceAlignment' of object '#<Object>'`

This also point to `useFieldArray`

**Comment by hannyle** [comment]
Close again as it's fixed with PR https://github.com/CSCfi/metadata-submitter-frontend/pull/344
