### ISSUE TITLE
Add tests for wizard layout

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#31]
#### Proposed solution

Wizard process isn't tested in any way currently, add some basic unit tests, later end-to-end

#### DoD (Definition of Done)

Wizard is extensively tested

#### Testing

Part of solution

**Comment by saulipurhonen** [comment]
I think this can be closed since we are testing UI in both integration and e2e tests. 
@blankdots, any opinions?

**Comment by blankdots** [comment]
I think for this to be fully complete we need to retrieve the folder that has been submitted in the home page listing. But most likely we probably need a different test for that.

However yes this could be considered fixed with #108

**Comment by blankdots** [comment]
this was already tested in #108 but we can add as part of this testing with min 2 forms/objects (e.g. study and analysis) being filled in and added to the submission as an extension of the end 2 end tests.
it should also check summary that it contains the right amount of objects that have been saved.
