### ISSUE TITLE
Duplicate headings

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#318]
#### Describe the bug

Some schemas have nested properties with same name as parent.

#### To Reproduce

Steps to reproduce the behaviour:

1. Open `Experiment` form
2. Choose `Pool` for `Sample Reference` in `Design` section
3. See duplicate heading

#### Expected behavior

Duplicate headings should be removed or presented in a way that it doesn't look like an error.

#### Screenshots

![image](https://user-images.githubusercontent.com/48789543/119344015-d425c880-bc9f-11eb-808e-259aa09ff011.png)

**Comment by blankdots** [comment]
this might be a back-end issue with data, will look into it.

**Comment by blankdots** [comment]
fixed in https://github.com/CSCfi/metadata-submitter/commit/eafc1d0db23904e3611e6e2a48127cbb624c0f0b

**Comment by hannyle** [comment]
I want to add here another related bug that I noticed:
In `Experiment` schema, both `"spotDescriptor"` and `"libraryDescriptor"` have the same `title` as `Library Descriptor`

**Comment by blankdots** [comment]
ok i will fix that as well

**Comment by blankdots** [comment]
duplicate library descriptor fixed.
i think we can close this, if there aren't any other issues
