### ISSUE TITLE
Draft object patch overwrite

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#321]
#### Describe the bug

Patching draft object doesn't overwrite values for fields that should have only one value. This can cause problems when populating form default values.

Overwrite works when submitting object so I think this might be related to backend.

#### To Reproduce

Steps to reproduce the behaviour:

1. Fill a `Sample` form with `Sample Data Type`
2. Save draft
3. Go to `Choose from drafts` and edit draft created in first step
4. Change `Sample Data type` from previous value and fill required field
5. Update draft
6. Go to `Choose from drafts` and edit draft created in first step
7. Inspect database for newly created draft object
8. See multiple key/value pairs in `sampleData`

#### Expected behavior

OneOf fields with only one possible value should be overwritten when draft object is patched

#### Screenshots

![image](https://user-images.githubusercontent.com/48789543/119641729-a026e080-be22-11eb-9588-14a0e872d649.png)

**Comment by saulipurhonen** [comment]
This seems to work now.

**Comment by saulipurhonen** [comment]
This problem happens on branch `bugfix/edit-does-not-work-for-all-fields`. It seems to be related to form populating and it keeps passes the old value on object patch actions. Also noticed that this does happen in both draft and submitted object scenarios.

Should this be handled in before patching or should backend catch this?

**Comment by blankdots** [comment]
:thinking: will look into it and come back with some ideas, as not sure in fully understand if this is front or back issue

**Comment by blankdots** [comment]
@saulipurhonen could I get an example of the `patch` requests made to the backend, will help me better debug this.

**Comment by saulipurhonen** [comment]
@blankdots `PATCH` request payload for draft Sample:
`{"sampleName":{"taxonId":1234},"sampleData":{"gender":"male","dataDescription":"test description"},"status":"Draft"}`

**Comment by saulipurhonen** [comment]
So there's both `gender` and `dataDescription` attributes. What I'm thinking is we have two options:

1) Keep only the latest one of and mutate the object in frontend before patching.
2) Backend compares payload to earlier data and makes mutation there.

**Comment by blankdots** [comment]
the patch in backend does: https://docs.mongodb.com/manual/reference/operator/update/set/ ... might be that i need to pre-process the query to make in the format mongo wants

**Comment by blankdots** [comment]
regarding this, I think it is combination of back-end and front-end issue, as front-end wants to do a PATCH but data is already there so it does the usual operation and tries to add stuff, which does not overwrite what is already there.
the options that @saulipurhonen made sounds reasonable, and based on the request that are sent to the back-end i think this should be treated in front-end

- request 1- Save Draft
```
{'title': 'asdasgdasg', 'sampleName': {'taxonId': 34654746, 'scientificName': 'asfdasghfdshjd', 'commonName': 467756856}, 'description': 'sgsghdg', 'sampleData': {'gender': 'unknown'}, 'status': 'Draft', 'accessionId': '6138e294c6634e5d8fc13ec417857245', 'dateModified': datetime.datetime(2021, 7, 2, 8, 52, 50, 330483)}
```

- request 2- Update Draft

```
{'title': 'asdasgdasg', 'sampleName': {'taxonId': 34654746, 'scientificName': 'asfdasghfdshjd', 'commonName': 467756856}, 'description': 'sgsghdg', 'sampleData': {'gender': 'unknown', 'dataDescription': 'dshfdjhgfjfhkhfkjf'}, 'status': 'Draft', 'accessionId': '6138e294c6634e5d8fc13ec417857245', 'dateModified': datetime.datetime(2021, 7, 2, 8, 53, 23, 670376)}
````

In request 2 the `gender` key should not be there any more

**Comment by blankdots** [comment]
so the change we need to make might be in https://github.com/CSCfi/metadata-submitter-frontend/blob/develop/src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js#L386
and  Keep only the latest one of and mutate the object in frontend before patching.

**Comment by hannyle** [comment]
That sounds reasonable to me. I also think that it's more optimal to handle this from the client side.
