### ISSUE TITLE
DAC Contact telephone number doesn't validate as integer

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#332]
#### Describe the bug

Contact telephone number format is string in DAC schema. Form doesn't validate if user tries to add only numbers to `Contact Telephone number` field.

#### To Reproduce

Steps to reproduce the behaviour:

1. Go to 'DAC' form
2. Fill `Contacts` details and add only numbers to `Contact Telephone Number` field
3. Submit form
4. See validation error

#### Expected behavior

~`Contact Telephone Number` field should accept integers.~
`Contact Telephone Number` field value should be handled as string when saving / submitting form.

**Comment by blankdots** [comment]
that might be problematic as there are different ways of writing phone numbers
e.g. `"(888)555-1212"` `+38385629845` `0038457284578` so i think string is appropriate.

**Comment by saulipurhonen** [comment]
That's right. I think we need to parse field to string if value is integer. I'll edit `Expected behavior` on this issue.

**Comment by blankdots** [comment]
![image](https://user-images.githubusercontent.com/47524/122865746-88fae600-d32f-11eb-8021-e6ede562435f.png)
that regex matches seems to provide a desired functionality will try to put in backend

**Comment by blankdots** [comment]
however judging from back-end implementation this does not seem to be issue there because we do have DAC with just numbers ... https://github.com/CSCfi/metadata-submitter/blob/develop/tests/test_files/dac/dac.xml#L6-L7

**Comment by saulipurhonen** [comment]
> however judging from back-end implementation this does not seem to be issue there because we do have DAC with just numbers ... https://github.com/CSCfi/metadata-submitter/blob/develop/tests/test_files/dac/dac.xml#L6-L7

I tried to check but didn't see if we validate test files against schema in backend integration tests? Or if we do, how does it pass since field is typed to string?

**Comment by blankdots** [comment]
> I tried to check but didn't see if we validate test files against schema in backend integration tests? Or if we do, how does it pass since field is typed to string?

all files validate test files against json-schema even xml ones (we parse them to JSON and validate them)

**Comment by saulipurhonen** [comment]
> > I tried to check but didn't see if we validate test files against schema in backend integration tests? Or if we do, how does it pass since field is typed to string?
> 
> all files validate test files against json-schema even xml ones (we parse them to JSON and validate them)

Ah yes. So it gets converted to string when parsing to JSON.

**Comment by blankdots** [comment]
there https://github.com/CSCfi/metadata-submitter/pull/233 which adds the regex hope it helps even a tiny bit
