### ISSUE TITLE
Add snackbar for consistent app wide notifications

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#34]
#### Proposed solution

Show notifications in snackbar instead of rendering them inside components. However, if notification type is closely related to that component (e.g. field errors in forms), keep those notifications rendered in components. 

See material ui snackbar info https://material-ui.com/components/snackbars/

#### DoD (Definition of Done)

Snackbar implemented

#### Testing

unit test & end to end

**Comment by saulipurhonen** [comment]
This is somewhat done already but we can improve current codebase with few adjustments.

We have component for status message handling which shows errors in snackbar. We could modify this component to take parameter that indicates if message needs to be shown in snackbar.

I think we could use a redux state to trigger and add content for snackbar in status message handler and place the component in root of NewDraftWizard.
