### ISSUE TITLE
Refactor API response error handling to one component 

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#37]
#### Proposed solution

Response error handling is current done similarly in both json and xml forms. Error handling + notifications about errors can be extracted to same component and notifications can be done with snackbar.

#### DoD (Definition of Done)

No duplicate error handling

#### Testing

unit tests

**Comment by otahontas** [comment]
- error checking is scattered all around in different components, would be good to have some centralized method to a) check errors and b) report them as snackbar notifications. This is needs a lot of refactoring

**Comment by saulipurhonen** [comment]
Both form and XML upload components have also duplicate code for information and success handling. Moved this all duplicate status handling logic to separate component.
