### ISSUE TITLE
Make it easy to find drafts and submit them

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#409]
#### Description

As a user i am not able to see my drafts and follow through with the submissions.

We can move the `Choose from drafts`
![image](https://user-images.githubusercontent.com/47524/128664003-e2496a7f-b09b-467b-ab78-0466622fb29f.png)

on the right with the submitted objects under different sections
![image](https://user-images.githubusercontent.com/47524/128664059-d0c86180-d61d-47a3-a993-f576944f3430.png)
We can also add to the button group there `Submit` so that we have `Submit, Continue, Delete`

**Note: other ideas are welcomed**

#### DoD (Definition of Done)

Move drafts to a location where users can easily find them

#### Testing

Unit and Integration testing

**Comment by saulipurhonen** [comment]
> We can also add to the button group there Submit so that we have Submit, Continue, Delete
How would we like to handle `Submit` button click on drafts that aren't eligible for submission? E.g. draft can be missing required fields.

I'm thinking couple options:
1) We can try to validate draft data on `Submit` button click and show a message if form needs to be edited before submission. 
2) Force user to edit form if user want's to submit draft

**Comment by blankdots** [comment]
2nd option sound easier and has implication that the user actually sees the form when they try to submit it.
personally i would go with that.

**Comment by saulipurhonen** [comment]
This however can affect performance, since we need to validate data before sending it to object API

> 2nd option sound easier and has implication that the user actually sees the form when they try to submit it.
> personally i would go with that.

Sounds good to me since validating draft data affects performance at some level. Also trying to submit invalid form in edit view gives better sight to what needs to be changed.
