### ISSUE TITLE
wrong total number of pages when listing folders

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#422]
#### Describe the bug

It seems wrong number of pages is displayed in the UI

#### To Reproduce

Steps to reproduce the behaviour:

1. add 2 draft folders
2. Go to e.g `http://localhost:3000/home/drafts`
3. See `1-2 of 2` - which is confusing as expected was the number of pages not the number of results

#### Expected behavior

Expected to see `1 of 1` or `{age 1 of 1 |  Total Drafts: 2`

#### Screenshots

![image](https://user-images.githubusercontent.com/47524/129241427-a87f0481-e7d5-4fd8-ae35-f4be523848dd.png)

#### Additional context

the backend seems to return ok:
```
{"page":{"page":1,"size":10,"totalPages":1,"totalFolders":2}}
```

**Comment by blankdots** [comment]
Update: as @saulipurhonen pointed out it seems to be correct: https://material-ui.com/components/pagination/#table-pagination however it is very confusing if it is displaying results, so we can improve with one of:
- add `Results` label in front
- move `1-2 of 2` to the left - thus separating from the pagination buttons
- do both of them (add label and move to left)

**Comment by saulipurhonen** [comment]
One way of achieving more intuitive interaction is to add pages text similar to:
![image](https://user-images.githubusercontent.com/48789543/129309951-4db55bc3-3e79-44a6-8b37-66176696be4e.png)
