### ISSUE TITLE
Updating of objects fails with "Update <Object>" button

### ISSUE THREAD

**Issue by lilachic** [CSCfi/metadata-submitter-frontend#433]
#### Describe the bug
When trying to update chosen object draft it errors.

#### To Reproduce

Steps to reproduce the behaviour:

1. Select draft submission on  main page
2. click to edit an object
3. update object
4. see error

#### Expected behavior

Updating of an object should happen without errors. 

#### Screenshots

https://user-images.githubusercontent.com/47525503/130409911-34d3a6d7-0e6f-4d59-bbf8-ca2fbe7830c7.mov

**Comment by lilachic** [comment]
There was also another minor bug: Warning: Failed prop type: The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed. This will be fixed with the above mentioned bug.

**Comment by lilachic** [comment]
Wondering why there are two different versions of cardheaders? Both are shown after clicking edit at homepage draft list. Fails with button “Update Study”, when study has button “Update draft” it works? This requires more investigating.
<img width="968" alt="Screenshot 2021-08-25 at 11 52 34" src="https://user-images.githubusercontent.com/47525503/130760519-cfe1094a-da61-47be-8b8d-af3b09fdcc20.png">

**Comment by hannyle** [comment]
There are two different versions of card headers because: one is editing **submitted** object, the other one is editing **draft** so when clicking `Update Study` or `Update draft`, there are two different functions handling each case.
The issue is with `Update Study` button so I think there are some issues with the **submitted** object that is patching.

**Comment by lilachic** [comment]
Thanks! For me it is confusing that those come after clicking edit under the same "Your Draft Submissions" list, different folders though.
