### ISSUE TITLE
Distinguish between accession ids

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#436]
#### Description

When selecting accession IDs it is not easy to identify which id belongs to which metadata object
![image](https://user-images.githubusercontent.com/47524/131353713-a6b676ff-0dd8-4688-b535-0b1815f07345.png)

#### DoD (Definition of Done)

add title information next to accession id to identify the accessionid

#### Testing

peer review

**Comment by hannyle** [comment]
So far only `Study` object type has `title` as required field, but for this issue I would assume we have `title` for all forms and we could make changes in back-end later.

**Comment by blankdots** [comment]
we cannot make title mandatory in all schemas in the back-end unfortunately, as this will trigger some undesired behaviour in validating XML schemas.

Could we require the title fields for all forms in the UI ?

**Comment by hannyle** [comment]
hm..i see. In this case I will try making the title as required field from front-end side.

For the XMLs I think timestamp may not be clear enough for the user to remember and distinguish them, adding title field could be a good way, or I'm also thinking to put the `file name + accessionId`

**Comment by blankdots** [comment]
`file name + accessionId` is fine as well
