### ISSUE TITLE
Support for ajv-i18n

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#489]
#### Description

As a follow-up of #21 we would need to enable support for ajv-i18n for the validator. In some cases e.g. Finnish we need to have a custom translation file. https://github.com/ajv-validator/ajv-i18n

#### DoD (Definition of Done)

Ajv JSON validator supports internationalization 

#### Testing

Integration testing

**Comment by saulipurhonen** [comment]
Finnish translations are now live in [ajv-i18n](https://github.com/ajv-validator/ajv-i18n) library.
