### ISSUE TITLE
Autocomplete full name based on family and given name for DOI creators and contributors 

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#501]
#### Description

follow-up of #455 

We want to autofill the name field with given and family name

example
![Peek 2021-10-20 10-51](https://user-images.githubusercontent.com/47524/138051149-5843b431-4e63-49a9-9fbd-1f948873b838.gif)
 

#### DoD (Definition of Done)

name field is disabled and filled as in the example

#### Testing

Unit or integration tests

**Comment by hannyle** [comment]
Could we have from the datacite schema's `properties` or `title` either `familyName` or `lastName` ? They are kind of mixing at the moment.

**Comment by blankdots** [comment]
> Could we have from the datacite schema's `properties` or `title` either `familyName` or `lastName` ? They are kind of mixing at the moment.

Not sure i follow, because in datacite there is no `title` if i remember correctly ... we need for e.g. creator these 2 https://github.com/CSCfi/metadata-submitter/blob/develop/metadata_backend/helpers/schemas/datacite.json#L17-L24 to be entered into field https://github.com/CSCfi/metadata-submitter/blob/develop/metadata_backend/helpers/schemas/datacite.json#L25-L28

**Comment by hannyle** [comment]
Sorry I didn't make it clear enough, what I meant is quite simple. Is it possible if we only use either `Last name` or `Family name` so it is easier for user to follow.

![Screenshot 2021-11-08 at 9 10 19](https://user-images.githubusercontent.com/23532204/140699323-abb6a875-9452-492f-89de-7c4eb8b9013a.png)

**Comment by blankdots** [comment]
issue with last name and family name should be fixed with: https://github.com/CSCfi/metadata-submitter/pull/279
