### ISSUE TITLE
New login page

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#531]
#### Description

as part of move to new design styles #363 we need a new UI page
https://www.figma.com/file/NJiSfMKCPMJZIduAYVq0he/SD-vs-2?node-id=0:1

@hannyle to provide image

example page also from https://sd-desktop.csc.fi

#### DoD (Definition of Done)

New login page fits the design

#### Testing

Peer review

**Comment by hannyle** [comment]
![csc_banner_login](https://user-images.githubusercontent.com/23532204/140871004-63bd7923-ba1a-4c7d-b207-43b1e30a5e9a.png)
