### ISSUE TITLE
New navigation bar

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#532]
#### Description

as part of move to new design styles #363 we need a new navigation bar that adheres to:
https://www.figma.com/file/NJiSfMKCPMJZIduAYVq0he/SD-vs-2?node-id=0:1

language is going be under the username

![image](https://user-images.githubusercontent.com/47524/142606705-649d1b6b-6d86-47a1-a3c5-911fc3600ee4.png)

#### DoD (Definition of Done)

New navigation bar

#### Testing

Peer review

**Comment by hannyle** [comment]
A later improvement in design will have a new follow-up issue.
