### ISSUE TITLE
Rename "new draft" related items

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#535]
#### Proposed solution

Legacy names for "new draft" should be renamed to "submission" as discussed in #533.

This should be done to all UI components, routes and variables where this naming has more accurate meaning.

#### DoD (Definition of Done)

Legacy names for "new draft" have been renamed to "submission"

#### Testing

Update tests to match new naming.

**Comment by rquazi** [comment]
So, just to be absolutely sure NewDraftWizard should be renamed as SubmissionWizard and also in routes like  <Route path="/newdraft" ....>

**Comment by blankdots** [comment]
yes.
