### ISSUE TITLE
Accordion menu on the left

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#538]
#### Description

Implement in the accordion with the 4 steps and objects groups
https://www.figma.com/file/NJiSfMKCPMJZIduAYVq0he/SD-vs-2?node-id=0%3A1

Add button is included for objects.

![image](https://user-images.githubusercontent.com/47524/142605918-efd691fb-1e47-4478-b6f3-506ec25cfe24.png)

A bottom stepper is needed:

![image](https://user-images.githubusercontent.com/47524/142656023-61fd8df9-b363-4197-8ea0-62f3a06af616.png)

#### DoD (Definition of Done)

Accordion contains the 4 steps and the tree structure of the objects

#### Testing

Unit and integration testing

**Comment by hannyle** [comment]
Update with the first step is creating a submissions:
![Submission details (2)](https://user-images.githubusercontent.com/23532204/155957243-da0e9e29-ca3a-4ef0-83ea-4ba0414d2bf9.png)

**Comment by hannyle** [comment]
The badge to mark the file is `Ready` has been changed to this:
![Screenshot 2022-02-28 at 11 26 14](https://user-images.githubusercontent.com/23532204/155958220-022a900a-19ce-415b-bbfa-0c204b44e016.png)

**Comment by juhtornr** [comment]
@saulipurhonen we moved this back to backlog as to our knowledge you are working for different project for next two weeks.
