### ISSUE TITLE
Redesign main page with drafts and published 

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#539]
#### Description

Follow the template at https://www.figma.com/file/NJiSfMKCPMJZIduAYVq0he/SD-vs-2?node-id=0%3A1

![image](https://user-images.githubusercontent.com/47524/142654812-c0d8fdbf-184e-44a0-ae88-8ddc350cc262.png)

#### DoD (Definition of Done)

New main page with drafts and published folders/submissions

#### Testing

Unit and integration tests

**Comment by hannyle** [comment]
![Screenshot 2022-02-18 at 14 57 32](https://user-images.githubusercontent.com/23532204/154687162-68ce185c-5192-49a1-81f2-c121415166a9.png)
