### ISSUE TITLE
make DAC Description as title field

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#545]
#### Description

with https://github.com/CSCfi/metadata-submitter/pull/299 the `title` field became mandatory and we would like to move from existing textfield

![image](https://user-images.githubusercontent.com/47524/144045712-6d8e0519-0776-4a34-876f-2f5824788dfd.png)

to a Title input field e.g.
![image](https://user-images.githubusercontent.com/47524/144046025-1d33ad03-83ef-4369-a15f-7b7e11c2c609.png)

#### DoD (Definition of Done)

DAC JSON schema title renders now to `input` field instead of `textarea`

#### Testing

unit and integration tests

**Comment by blankdots** [comment]
in backend we can rename to `DAC Title` when this change will happen.

**Comment by blankdots** [comment]
backend changes included as part of: https://github.com/CSCfi/metadata-submitter/pull/323

**Comment by hannyle** [comment]
When the `DAC Description` changed to `DAC Title`, the field was automatically switched from `textarea` to `input` by a filter in frontend. So I think it does not need to fix.

**Comment by blankdots** [comment]
good, then we can close.
