### ISSUE TITLE
Fix user not being able to submit form when there are validation errors on non-required fields

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#56]
#### Describe the bug

Form validation is run also on non-required fields, even when they're empty. This is probably because form fields have defaultValue set to "" and field errors are reported against this value.

#### To Reproduce

Steps to reproduce the behaviour:

1. Go to study json form
2. Don't fill anything to pubmed ID or study abstract
3. Click submit
4. See error messages

#### Expected behavior

Don't show error messages if field isn't required and is not in use. 

#### Screenshots

**Comment by blankdots** [comment]
Probably worth validating a field if
1. always if it required
2. has any data in it, excluding empty string
