### ISSUE TITLE
Adapt Integration tests to new JSON schema structure

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#622]
#### Description

https://github.com/CSCfi/metadata-submitter/pull/323 has introduced new changes for Experiment and Run, among new descriptions and other changes.

`Label` has been remove from References and the focus now should be on `AccessionID`

![image](https://user-images.githubusercontent.com/47524/148850611-34a3a6a7-a8e4-4f56-aeb6-eab8dffc56c7.png)

The `Processing` field can be omitted .

#### DoD (Definition of Done)

Adapt integration tests so that they still pass based on the PR https://github.com/CSCfi/metadata-submitter/pull/323

#### Testing

Integration tests

**Comment by hannyle** [comment]
Could we omit `"required": [
                        "pipeSection"
                    ]` in `Run` and `Experiment` schemas ? I think it's not necessary to require it as `Processing` field is not required neither.

**Comment by blankdots** [comment]
> Could we omit `"required": [
>                         "pipeSection"
>                     ]` in `Run` and `Experiment` schemas ? I think it's not necessary to require it as `Processing` field is not required neither.

i will take a look, we might.

**Comment by blankdots** [comment]
Done. changes should be in https://github.com/CSCfi/metadata-submitter/pull/323 branch.
