### ISSUE TITLE
Implement showing info about saved objects in wizard

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#68]
#### Proposed solution

Saved objects should be listed on the right side of screen (like in UI sketch version 4). 

#### DoD (Definition of Done)

Objects are listed

**Comment by saulipurhonen** [comment]
On UI sketch layout it states on the right side component "Submitted study forms". There seems not to be a way to tell from submitted object what is the objects type (form, xml, existing). I see couple options here:
A) Change the title to "Submitted study objects"
B) Add object type to saved object data metadataObjects item. This item consists now from accessionId and schema fields.

@blankdots , @csc-jm any opinions?

**Comment by blankdots** [comment]
@saulipurhonen good point. I think option B would be the way to go. I will go over the APIs we have and also I think we will be needing that draft folders endpoint for this.
