### ISSUE TITLE
Set up better way to disable folder creation form after first step of wizard

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#69]
#### Proposed solution

Currently if folder is saved of redux store and user click themselves back to first wizard dstep, a "fake form" is rendered. Proper solution would be to disable fields in real form and add possibility to edit folder name and description if user wants to.

#### DoD (Definition of Done)

A real form is rendered, not any fake ones.

**Comment by saulipurhonen** [comment]
@blankdots, @csc-jm is there a good reason why folder creation elements need to be disabled when the redux store item is created? Would it be logical to keep the form elements enabled all the time and just update corresponding store item if user chooses to change folder name or description?

**Comment by csc-jm** [comment]
Yea I see no problem with locking that first step of the wizard as our backend currently allows the folder name and description to be edited as well after the folder has been created

**Comment by blankdots** [comment]
@saulipurhonen 
> Would it be logical to keep the form elements enabled all the time and just update corresponding store item if user chooses to change folder name or description?

Yes, it is a good idea.
