### ISSUE TITLE
Create reusable confirmation alerts for wizard

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#70]
#### Proposed solution

Add reusable components to be used when user cancels wizard or changes form, so components aren't copypasted between views. 

#### DoD (Definition of Done)

Reusable confirmation alert component is created and used in proper places.

**Comment by saulipurhonen** [comment]
Merged with https://github.com/CSCfi/metadata-submitter-frontend/issues/72
