### ISSUE TITLE
Make form closing alert to work more consistently

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#72]
#### Proposed solution

Currently form closing alert is rendered inside objectindex-component when user clicks for another submission type and is already on some form. This, however is not ideal solution since user can
- click on next or previous, which dispatches another wizard step
- click on cancel the whole form
- click on save and exit

All of these should trigger some alert, so probably it's best to move alert handling to some centralized place.

Also alert content should work differently and have different content when user is in xml upload form or in add existing object -form.

#### DoD (Definition of Done)

Form closing works consistently. Reusable confirmation alert component is created and used in proper places.

**Comment by saulipurhonen** [comment]
Merging this issue with previous alert issue https://github.com/CSCfi/metadata-submitter-frontend/issues/70
In both issues an alert component needs to be created and rendered with details depending on parent component.
