### ISSUE TITLE
Replace custom ajv resolver with official when official is released

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#73]
#### Proposed solution

Current version of ajv resolved is based on PR in https://github.com/react-hook-form/resolvers repo. Replace our custom one with official when official is released.

#### DoD (Definition of Done)

Official resolved is used.

**Comment by blankdots** [comment]
It seems it is still work in progress as of: https://github.com/react-hook-form/resolvers/pull/59

It was originally merged then reverted as pointed out here: https://github.com/react-hook-form/resolvers/issues/112
