### ISSUE TITLE
Update new way to get datacite schema

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter-frontend#768]
#### Proposed solution

Based on changes in backend https://github.com/CSCfi/metadata-submitter/pull/400, `datacite` schema was removed. It's now under `folders` schema only and we should fetch it from `folders` schema.

#### DoD (Definition of Done)

Datacite schema is fetched from `folder.json["doiInfo"]` 

#### Testing

Current unit tests and integration tests should cover this issue.

**Comment by blankdots** [comment]
we can still retrieve the datacite schema using the same endpoint nothing changed there so, this should not impact anything just tested stuff still work with that change

**Comment by hannyle** [comment]
> we can still retrieve the datacite schema using the same endpoint nothing changed there so, this should not impact anything just tested stuff still work with that change

Thanks, I was thinking too far. I tested and it should be fine, so I close this issue.
