### ISSUE TITLE
Implement design for XML upload

### ISSUE THREAD

**Issue by ainoc** [CSCfi/metadata-submitter-frontend#787]
- [ ] Loading screen needs to be added to the flow
- [ ] Highlight state for drag and drop
- [ ] Remove Options

**Comment by hannyle** [comment]
Design for XML: https://www.figma.com/proto/NJiSfMKCPMJZIduAYVq0he/SD-Submit-Prototype-2?page-id=3279%3A18679&node-id=3279%3A18811&viewport=259%2C48%2C0.14&scaling=min-zoom&starting-point-node-id=3279%3A19001
