### ISSUE TITLE
Adapt frontend to use new endpoint for DOI information submission instead of folder patch

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter-frontend#799]
#### Description

Adapt frontend to use new DOI info submission endpoint instead of patch call to folder.
The endpoint is `/submission/{submission}/doi`, which will accept Datacite information in a request body as JSON.

#### DoD (Definition of Done)
The frontend uses a designated API endpoint for adding Datacite information to the folder.

#### Testing
At least integration tests

**Comment by csc-felipe** [comment]
Here's the PR with the change in the backend.
https://github.com/CSCfi/metadata-submitter/pull/450
