### ISSUE TITLE
Update vulnerable packages

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/metadata-submitter-frontend#88]
#### Proposed solution

run "npm audit" in CLI
Audit results in high severity vulnerabilities. These should be fixed

#### DoD (Definition of Done)

Audit results in no high risk vulnerabilities.

#### Testing

run "npm audit" in CLI

**Comment by blankdots** [comment]
this should fix it: `npm install react-scripts@4.0.0` however that breaks the tests ... :thinking:

**Comment by saulipurhonen** [comment]
> this should fix it: `npm install react-scripts@4.0.0` however that breaks the tests ... 🤔

Yeah, react-scripts@4.0.0 includes some breaking changes. Haven't got time to check it through yet.
