### ISSUE TITLE
Add titles to submitted items list

### ISSUE THREAD

**Issue by lilachic** [CSCfi/metadata-submitter-frontend#94]
In continuation to https://github.com/CSCfi/metadata-submitter-frontend/pull/92 it would be nice to have titles in the list to group submitted items by titles like "Submitted study forms", so "`Submitted <objectType> <submissionType>" .
`
#### DoD (Definition of Done)
When list titles appear.

**Comment by saulipurhonen** [comment]
I think this was discussed before and isn't possible until metadataObjects have objectType property in database.

**Comment by blankdots** [comment]
@saulipurhonen  What is `objectType property` ?

**Comment by saulipurhonen** [comment]
> @saulipurhonen What is `objectType property` ?

@blankdots by `objectType property` I mean that we should have object type (eg. Form, XML) stored in the folders `metadataObjects`.

As for now the structure is:
`        {
            "accessionId": "123123",
            "schema": "study"
        }`
        
And should be:
`        {
            "accessionId": "123123",
            "schema": "study",
            "objectType": "XML"
        }`

**Comment by blankdots** [comment]
I see.
The suggestion of having `Submitted <objectType> <submissionType>` confused me as i think `objectType` refers to something like e.g. `study`, `anlysis` and corresponds to the `schema` and the `submissionType` to the source of input.

O think `submissionType` or `objectSource` with values in either `XML` or `Form` might make more sense. what do you think ?

**Comment by saulipurhonen** [comment]
@blankdots,  it seems that I got this wrong from the beginning. I was referring `objectType` wrongly to `submissionType`. This can be also seen in `WizardSavedObjectsList` component. I made a bug issue for this: #142 

I think `submissionType` would suit best for the key name.

**Comment by blankdots** [comment]
ok, I will try to implement that in the backend - but it will be an optional key `submissionType` in `folders` `drafts` and `metadataObjects` objects.
Now comes the question: what should set that key value, front-end or back-end ?

My 2 cents is that, while back-end could set that, it will most likely not be used anywhere so it will only have value for front-end

**Comment by hannyle** [comment]
I think since `submissionType` only has value for front-end, and it won't be difficult to add it to the `object`. We can implement that from front-end side.

**Comment by blankdots** [comment]
I added something like this to `metadataObjects` and `drafts` in `fodlers` to make it more extensible. Notice the `tags` key where anything can be added and used by front-end but by default only `submissionType` can take either `XML` or `Form`

```
"metadataObjects": [{"accessionId": "id", "schema": "study", "tags": {"submissionType": "XML"}}]

```
Update can happen like
```
{
                "op": "add",
                "path": "/metadataObjects/-",
                "value": {"accessionId": "id", "schema": "study", "tags": {"submissionType": "XML"}},
}
```

Would this work ?

**Comment by saulipurhonen** [comment]
@blankdots, looks good to me.

**Comment by hannyle** [comment]
@blankdots I think it is good enough. So, is `tags` an optional property, for example if we do the update ?

**Comment by blankdots** [comment]
@hannyle yes `tags` is optional property of type object and can contain any number of key value pairs, but only one is specified `submissionType` that can be either `XML` or `Form`, you can see this PR https://github.com/CSCfi/metadata-submitter/pull/181 - which you can review if you want sooner to be in `develop` branch or we can wait for @teemukataja  to review it :)
