### ISSUE TITLE
Fix keyboard tab order XML file upload, Choose file button

### ISSUE THREAD

**Issue by lilachic** [CSCfi/metadata-submitter-frontend#98]
#### Describe the bug

This is continuation to Fix keyboard-based xml file upload #20. When the user has chosen to upload XML file, it would be nice to move focus directly to "Choose file" button instead of tabbing all the objectTypes in accordion first.

#### To Reproduce

Steps to reproduce the behaviour:

1. Select an object type by tab and enter
2. Select submission type by tab, tab and enter
3. many tabs to reach "Choose file button"

#### Expected behavior

1. Select an objectType by tab and enter
2. Select submission type by tab tab and enter
3. Focus is on "Choose file"

#### A note
This could be checked with all the buttons.

**Comment by saulipurhonen** [comment]
One problematic case that comes to mind is if user want to preview submission form / upload.

1. User chooses submission type
2. Focus goes to form / upload
3. User has to tab back to object index

Proposed solution:

1. Choose submission type with enter key
2. A skip-link is shown between next and chosen submission type
3. Focus goes to form / upload when navigating from skip-link

Any ideas @blankdots, @hannyle, @lilachic?

**Comment by hannyle** [comment]
> One problematic case that comes to mind is if user want to preview submission form / upload.
> 
> 1. User chooses submission type
> 2. Focus goes to form / upload
> 3. User has to tab back to object index
> 
> Proposed solution:
> 
> 1. Choose submission type with enter key
> 2. A skip-link is shown between next and chosen submission type
> 3. Focus goes to form / upload when navigating from skip-link
> 
> Any ideas @blankdots, @hannyle, @lilachic?

If I understood correctly, your proposed solution is that we use the `Skip-link` to focus on form/upload. If we want go back to Object index or choose another submission type, we use `Enter key` ?

**Comment by saulipurhonen** [comment]
> > One problematic case that comes to mind is if user want to preview submission form / upload.
> > 
> > 1. User chooses submission type
> > 2. Focus goes to form / upload
> > 3. User has to tab back to object index
> > 
> > Proposed solution:
> > 
> > 1. Choose submission type with enter key
> > 2. A skip-link is shown between next and chosen submission type
> > 3. Focus goes to form / upload when navigating from skip-link
> > 
> > Any ideas @blankdots, @hannyle, @lilachic?
> 
> If I understood correctly, your proposed solution is that we use the `Skip-link` to focus on form/upload. If we want go back to Object index or choose another submission type, we use `Enter key` ?

Correct, except I think user should tab back to object index if chosen to navigate with `skip-link`.

Link should be visible only if user has selected object type with `enter` key. Link disappears when navigated with skip-link or user has selected another submission type (link re-appears beneath new submission type label.

Here's a rough sketch:
![image](https://user-images.githubusercontent.com/48789543/103526083-ffdb1a00-4e88-11eb-9296-85394553ef55.png)

**Comment by hannyle** [comment]
Sounds a good solution to me. Users can have more control whether they want to continue navigating or access to the form/upload

**Comment by blankdots** [comment]
@saulipurhonen solution LGTM to me as well, we can work out the styling later
